name: "phplint"

on:
  push:
    paths-ignore:
      - 'doc/**'
  pull_request:
    paths-ignore:
      - 'doc/**'

jobs:
  tests:
    name: "Lint"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - "8.0"
          - "latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          extensions: "intl"
          ini-values: "memory_limit=-1, error_reporting=E_ALL, display_errors=On"
          php-version: "${{ matrix.php-version }}"

      - name: "Lint PHP files"
        run: "find app/ -type f -name '*.php' -print0 | xargs -0 -L1 -P4 -- php -l -f"
